name: Setup Swift
description: Setup a Swift environment on Ubuntu or macOS 
author: Frederik Wallner
inputs:
  swift-version: 
    description: Swift version to configure
    required: true
    default: '5.10'
outputs:
  version:
    description: The full Swift version that was configured
runs:
  using: node16
  main: dist/index.js
branding:
  icon: 'command'  
  color: 'orange'
